<?php
$provider = $this->getParam('provider', '');
?>
<label for="oauth2<?php echo $this->escape(ucfirst($provider)); ?>ClientId">Application (Client) ID<span class="tooltip" data-tooltip="Client ID defined by user upon creation in Keycloak."><i class="icon-info-circled"></i></span></label>
<input name="appId" id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>ClientId" type="text" autocomplete="off" data-ls-bind="{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Appid}}" placeholder="Client ID" />
<?php /*Hidden input for the final secret. Gets filled with a JSON via JS. */ ?>
<input name="secret" data-forms-oauth-custom="<?php echo $this->escape(ucfirst($provider)); ?>" id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Secret" type="hidden" autocomplete="off" data-ls-bind="{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Secret}}" />
<!-- [Your custom form inputs go here] -->
<label>Authorization Endpoint</label>
<input id="oauth2KeycloakAuthEndpoint" type="text" placeholder="https://<Keycloak Base URL>/realms/<your realm>/protocol/openid-connect/auth">
<label>Token Endpoint</label>
<input id="oauth2KeycloakTokenEndpoint" type="text" placeholder="https://<Keycloak Base URL>/realms/<your realm>/protocol/openid-connect/token">
<label>UserInfo Endpoint</label>
<input id="oauth2KeycloakUserInfoEndpoint" type="text" placeholder="https://<Keycloak Base URL>/realms/<your realm>/protocol/openid-connect/userinfo">
<label>EndSession Endpoint</label>
<input id="oauth2KeycloakEndSessionEndpoint" type="text" placeholder="https://<Keycloak Base URL>/realms/<your realm>/protocol/openid-connect/logout">
        